version: '3.8'
services:
  frontend:
    image: ghcr.io/bezidev/beziapp/evolved/frontend
    depends_on:
      - backend
    restart: always
    networks:
      beziapp:
        aliases:
          - frontend
    ports:
      - 127.0.0.1:5298:3000
  backend:
    image: ghcr.io/bezidev/beziapp/evolved/backend
    volumes:
      - ./uploads:/app/uploads
      - ./config.json:/app/config.json
      - ./doors.log:/app/doors.log
    environment:
      - TZ=Europe/Ljubljana
      - RINGO_TOKEN=${RINGO_TOKEN}
    restart: always
    networks:
      beziapp:
        aliases:
          - backend
    ports:
      - 127.0.0.1:5299:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  beziapp:
