version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      beziapp:
        aliases:
          - postgres
    volumes: 
      - ./database:/var/lib/postgresql/data
  nginx-proxy:
    depends_on:
      - frontend
      - backend
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    networks:
      beziapp:
        aliases:
          - nginx
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  frontend:
    image: ghcr.io/bezidev/beziapp/frontend
    depends_on:
      - backend
    networks:
      beziapp:
        aliases:
          - frontend
  backend:
    depends_on:
      - postgres
    image: ghcr.io/bezidev/beziapp/backend
    volumes:
      - ./refresh_token.txt:/app/refresh_token.txt
      - ./substitutions:/app/substitutions
      - ./uploads:/app/uploads
    environment:
      - MS_OAUTH_ID=${MS_OAUTH_ID}
      - MS_OAUTH_SECRET=${MS_OAUTH_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES=${POSTGRES}
    restart: always
    networks:
      beziapp:
        aliases:
          - backend
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx-proxy
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup
    depends_on:
      - nginx-proxy
      - backend
      - frontend
networks:
  beziapp:

volumes:
  certbot-etc:
  certbot-var:
  web-root:
